spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.5.36:8848
server:
  port: 9001

dubbo:
  scan:
    base-packages: com.hx.myshop.plus.business.web,com.hx.myshop.plus.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://182.92.5.36:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
business:
  oauth2:
    granttype: password
    clientid: client
    clientsecret: secret

# 开启 Feign 的 OKHttp 方式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true
