spring:
  application:
    name: cloud-message-admin-log
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 120.77.42.48:9876
        bindings:
          admin-login-log-topic: {consumer.orderly: true}
      bindings:
        admin-login-log-topic: {destination: admin-login-log-topic, content-type: text/plain, group: admin-login-log-group, consumer.maxAttempts: 1}

dubbo:
  scan:
    base-packages: com.hx.myshop.plus.message.consumer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://182.92.5.36:8848

server:
  # ${random.int[9000,9999]} 随机端口
  port: 20001
